version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: friday
      time: '20:00'
      timezone: Europe/London
    open-pull-requests-limit: 20
    reviewers:
      - stringbean
    assignees:
      - stringbean
    groups:
      runtime-dependencies:
        update-types:
          - minor
          - patch

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: friday
      time: '20:00'
      timezone: Europe/London
    reviewers:
      - stringbean
    assignees:
      - stringbean
    groups:
      GH-Actions:
        update-types:
          - minor
          - patch
